### ISSUE TITLE
Limit the # of parallel jobs in build

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/meta#306]
If a user specifies -j manually, it may crash the Jenkins CI system if the number exceeds the number of cpus.

We should either not allow the user to specify -j manually or inspect the options passed.

**Comment by v1gnesh** [comment]
In the recent case, it was the specification of a custom `ZOPEN_MAKE_OPTS`, rather than `ZOPEN_MAKE_MINIMAL=yes` that caused the non-addition of `ZOPEN_NUM_JOBS` to `ZOPEN_MAKE_OPTS`.

I was expecting `ZOPEN_NUM_JOBS` to be set in `setEnv()`, but looks like it didn't happen.
This should have done it:

```shell
if [ "${ZOPEN_NUM_JOBS}x" = "x" ]; then
  ZOPEN_NUM_JOBS=$("${utildir}/numcpus.rexx")

  # Use half of the CPUs by default
  export ZOPEN_NUM_JOBS=$((ZOPEN_NUM_JOBS / 2))
fi
```

Also note that if any custom `ZOPEN_MAKE_OPTS` is used at all, the -j flag isn't added at all.
```shell
if [ "${ZOPEN_MAKE_OPTS}x" = "x" ]; then
  export ZOPEN_MAKE_OPTS="-j${ZOPEN_NUM_JOBS}"
fi
```

Just looked it up and 'j' defaults to 1 when not specified.
>  The default number of job slots is one, which means serial execution (one thing at a time). 
https://www.gnu.org/software/make/manual/html_node/Parallel.html

... which is fine so long as we remain on 2 vCPU machines :)

**Comment by IgorTodorovskiIBM** [comment]
$ZOPEN_NUM_JOBS is set by zopen-build. You can confirm its value by adding this function in your buildenv:

```
zopen_init() {
  echo "Parallel job to run: $ZOPEN_NUM_JOBS"
}
```
The shell should evaluate $ZOPEN_NUM_JOBS when the make invocation is run.

**Comment by v1gnesh** [comment]
```shell
export ZOPEN_GIT_URL="https://github.com/duckdb/duckdb.git"
export ZOPEN_GIT_DEPS="cmake make comp_clang ninja zoslib"
export ZOPEN_TYPE="GIT"
export ZOPEN_COMP=CLANG

export ZOPEN_MAKE_OPTS="GEN=ninja -j\$ZOPEN_NUM_JOBS"
export ZOPEN_CONFIGURE="cmake"

zopen_init()
{
  echo "Parallel job to run: $ZOPEN_NUM_JOBS"
}
```

```shell
VERBOSE: 'Running zopen_init'
Parallel job to run: 1
Skip Bootstrap
VERBOSE: 'bootstap completed in 0 seconds.'
Running Configure
Using previous successful configuration. Specify -f to force a configure.
VERBOSE: 'configure completed in 0 seconds.'
Running Build
VERBOSE: '"make" GEN=ninja -j$ZOPEN_NUM_JOBS CC=clang "CPPFLAGS=-DNSIG=42
```

**Comment by MikeFultonDev** [comment]
think this is working ok now. @v1gnesh re-open if still broken.
