### ISSUE TITLE
zopen clean -a groff didn't do what i expected

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#426]
I have 3 packages in groff:

I was expecting zopen clean -a groff to clean up the ones I am not using. Here's what I got:

```
FULTONM@ZOSCAN2B bash ~> zopen clean -?
zopen clean is a utility for z/OS Open Tools to switch package versions for currently installed packages
Syntax: zopen-clean [<option>]* [<package]
  where <option> may be one or more of:
      -u : --unused: removes unused package versions
      -d : --dangling: removes dangling symlinks
      -c : --cache: cleans package cache
      -a : --all:  equivalent to -u -d -c
  -v: run in verbose mode.
TODO and <package> is a package name.
FULTONM@ZOSCAN2B bash ~> zopen clean -a groff
- Dangling link removal complete
- Cache at '/home/fultonm/zopen/var/cache/zopen' cleaned
FULTONM@ZOSCAN2B bash ~> #exit
FULTONM@ZOSCAN2B bash ~> zopen alt groff
1: groff-1.22.4.20230622_204353.zos
2: groff-1.22.4.20230918_154912.zos
3: groff-1.22.4.20230920_020202.zos  <-  current
```

Also - the help doesn't say what the default is if you don't specify an option...

@IgorTodorovskiIBM @DevonianTeuchter would appreciate your input

**Comment by MikeFultonDev** [comment]
Also, `zopen clean -u groff` was too aggressive - it removed all versions of groff even though I have man-db installed which uses it

**Comment by DevonianTeuchter** [comment]
Zopen clean -u <PKG> should leave the active version only - it shouldn't remove i if it was active so that's a puzzle. Wonder if the change to the install location didn't get picked up properly.
At the moment, there is no dependency checking at removal time so packages can be removed even if something else needs it - should be a separate issue against zopen-remove.
