### ISSUE TITLE
zopen clean -c

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/meta#616]
Enhance zopen clean -c to remove single cache package(s). Currently all packages are removed.
thanks

**Comment by IgorTodorovskiIBM** [comment]
Thanks, this issue and https://github.com/ZOSOpenTools/meta/issues/619 might make sense to handle in one PR

**Comment by gngrossi** [comment]
zopen clean -c could/should remove previous packages (pax files and directories)
thanks

# cache
${ROOTFS}/var/cache/zopen

# package directories
${ROOTFS}/usr/local/zopen

**Comment by DevonianTeuchter** [comment]
I actually have an updated zopen clean that enhances the --unused option (provides an --all to remove all packages' obsoleted versions and also to accept a list of packages rather than a singular entry - just needs some test cases written.  The cache and the alternative "store" are separate concepts really.
Allowing --cache & --unused in the same command (with package list or all) would give the requested behaviour whilst keeping each option dealing with it's relative component.
